const players = [
  {
    id: 1,
    name: 'Andres Pozo',
    imagePath: 'assets/images/team/andres_pozo.png',
    beers: 90,
    runs: 80,
    pubs: 96,
  },
  {
    id: 2,
    name: 'Carlitos',
    imagePath: 'assets/images/team/carlitos.png',
    beers: 90,
    runs: 90,
    pubs: 99,
  },
  {
    id: 3,
    name: 'David Bertholt',
    imagePath: 'assets/images/team/david_bertholt.png',
    beers: 90,
    runs: 90,
    pubs: 99,
  },
  {
    id: 4,
    name: 'Ema Oviedo',
    imagePath: 'assets/images/team/ema_oviedo.png',
    beers: 80,
    runs: 87,
    pubs: 90,
  },
  {
    id: 5,
    name: 'Eneas Forconi',
    imagePath: 'assets/images/team/eneas_forconi.png',
    beers: 70,
    runs: 90,
    pubs: 70,
  },
  {
    id: 6,
    name: 'Fede Diaz',
    imagePath: 'assets/images/team/fede_diaz.png',
    beers: 70,
    runs: 88,
    pubs: 70,
  },
  {
    id: 7,
    name: 'Fer Marengo',
    imagePath: 'assets/images/team/fer_marengo.png',
    beers: 88,
    runs: 90,
    pubs: 70,
  },
  {
    id: 8,
    name: 'Hugo Chavero',
    imagePath: 'assets/images/team/hugo_chavero.png',
    beers: 70,
    runs: 80,
    pubs: 70,
  },
  {
    id: 9,
    name: 'Javier Verblud',
    imagePath: 'assets/images/team/javier_verblud.png',
    beers: 70,
    runs: 80,
    pubs: 70,
  },
  {
    id: 10,
    name: 'Juan I. Ponce',
    imagePath: 'assets/images/team/juan_i_ponce.png',
    beers: 70,
    runs: 82,
    pubs: 70,
  },
  {
    id: 11,
    name: 'Lucas Godoy',
    imagePath: 'assets/images/team/lucas_godoy.png',
    beers: 90,
    runs: 88,
    pubs: 90,
  },
  {
    id: 12,
    name: 'Matias Roson',
    imagePath: 'assets/images/team/matias_roson.png',
    beers: 70,
    runs: 90,
    pubs: 70,
  },
  {
    id: 13,
    name: 'Matias',
    imagePath: 'assets/images/team/matias.png',
    beers: 88,
    runs: 92,
    pubs: 88,
  },
  {
    id: 14,
    name: 'Miguel M.',
    imagePath: 'assets/images/team/miguel_m.png',
    beers: 70,
    runs: 87,
    pubs: 70,
  },
  {
    id: 15,
    name: 'Nacho Mina',
    imagePath: 'assets/images/team/nacho_mina.png',
    beers: 70,
    runs: 96,
    pubs: 70,
  },
  {
    id: 16,
    name: 'Nano Molina',
    imagePath: 'assets/images/team/nano_molina.png',
    beers: 95,
    runs: 89,
    pubs: 88,
  },
  {
    id: 17,
    name: 'Nestor Medina',
    imagePath: 'assets/images/team/nestor_medina.png',
    beers: 80,
    runs: 80,
    pubs: 70,
  },
  {
    id: 18,
    name: 'Santiago B.',
    imagePath: 'assets/images/team/santiago_b.png',
    beers: 70,
    runs: 89,
    pubs: 70,
  },
  {
    id: 19,
    name: 'Fede Diaz Hero',
    imagePath: 'assets/images/team/fede_diaz_hero.png',
    beers: 90,
    runs: 95,
    pubs: 90,
  },
];

export default players;
